### ISSUE TITLE
Exception On Unplugging Microphone with DeviceStateChanged

### ISSUE THREAD

**Issue by AquaGeneral** [Belphemur/AudioEndPointLibrary#1]
In both SoundSwitch and an application I'm working on (C# based, with the AudioEndPointLibrary as part of the solution), there is a crash when a microphone is unplugged from the computer.

In debugging SoundSwitch, I can see the exception occurs in `AudioDevicePtr CAudioEndPointLibrary::GetAudioDevice` at line 104:

```
auto m_playback = this->GetPlaybackDevices(DefSound::EDeviceState::All);      
auto audio_device = std::find_if(m_playback.begin(), m_playback.end(), [pwstr_device_id](AudioDevicePtr device) {
    return wcscmp(device->ID, pwstr_device_id) == 0; // Line 104, crashes here
});
```

My knowledge if C++ is very limited but I noticed that the `pwstr_device_id` pointer is null when a microphone is unplugged. Unplugging a speaker or headphones the pointer is not null.

**Comment by Belphemur** [comment]
Hello Jesse, 

I'll give it a look this weekend. Thank you for the report.
